### ISSUE TITLE
Issue with codatify (TypeError from cd.stringify)

### ISSUE THREAD

**Issue by mzpqnxow** [tacnetsol/ida#24]
```Looking for possible strings starting at: REGINFO:0x400128...
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/codatify.py", line 376, in activate
    cd.stringify()
  File "C:/Program Files/IDA 7.0/plugins/codatify.py", line 260, in stringify
    if not idc.isASCII(idc.GetFlags(s.ea)) and idc.MakeStr(s.ea, idc.BADADDR):
  File "C:\Program Files\IDA 7.0\python\idc_bc695.py", line 113, in MakeStr
    def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea)
  File "C:\Program Files\IDA 7.0\python\idc.py", line 695, in create_strlit
    return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE))
  File "C:\Program Files\IDA 7.0\python\ida_bytes.py", line 1618, in create_strlit
    return _ida_bytes.create_strlit(*args)
TypeError: in method 'create_strlit', argument 2 of type 'size_t'%  ```

I have no experience with IDA plugins but I am competent with Python... but maybe there's an easy fix @devttys0  ?

**Comment by mzpqnxow** [comment]
This on IDA 7 x86, looking at MIPS, MIPS-I version 1

**Comment by mzpqnxow** [comment]
@devttys0 	I might just catch the TypeError and let it run for now... if you want to point me in the right direction I will try to fix it myself and PR

**Comment by mzpqnxow** [comment]
also FYI, this is on a busybox binary.. I caught the exception and the plugin (mostly) works and finishes cleanly (it recognizes that it didn't fixup everything well)

**Comment by eacmen** [comment]
+1 i also experience this issue

**Comment by alt-fox** [comment]
fixed like this

![image](https://user-images.githubusercontent.com/32519709/78863227-bec0f100-7a41-11ea-97ee-ce3bbacccd12.png)
